# Generated by Django 4.2.3 on 2023-07-07 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_is_verified_alter_booking_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
